title: Research Software Asia Australia Conference (RSAA26)

description: Research Software Asia Australia Conference (RSAA26)
baseurl: "" # the subpath of your site, e.g. /blog
github_repo:  rseaa
logo: images/rseaa_logo.png
markdown: kramdown  #github flavoured markdown
kramdown: 
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
permalink: pretty
theme: minima
plugins: 
  - jekyll-feed
include:
  - "_img"

# Navbar: ordered list of page paths (path relative to site root)
header_pages:
  - index.md
  - conferences/call_for_presentations.md
  - conferences/rsaa26_program.md
  - about/accessibility_fellowship.md
  - marketing/marketing.md
  - conferences/index.md

